name: Build Android APK H-M3U8
on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Versi Aplikasi H-M3U8'
        required: true
        default: '4.0.0'
      version_code:
        description: 'Kode Versi'
        required: true
        default: '4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Siapkan Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/assets --save-dev
          
      - name: Siapkan Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Proses Platform dan Izin (Android)
        run: |
          # 1. Hapus folder lama jika ada untuk cegah bentrok
          rm -rf android
          
          # 2. Buat ulang folder android (Ini yang menciptakan file Manifest)
          npx cap add android
          
          # 3. Suntik izin untuk M3U8 Scanner (Storage Permissions)
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" tools:ignore="ScopedStorage" />\n    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />' android/app/src/main/AndroidManifest.xml
          
          # Tambahkan xmlns:tools jika belum ada di manifest
          sed -i 's/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android"/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android" xmlns:tools="http:\/\/schemas.android.com\/tools"/g' android/app/src/main/AndroidManifest.xml
          
          # 4. Generate Ikon dan Splash
          npx capacitor-assets generate --android || true
          
          # 5. Sinkronisasi akhir
          npx cap sync android
          
      - name: Atur Versi Aplikasi
        run: |
          sed -i "s/versionCode [0-9]*/versionCode ${{ github.event.inputs.version_code }}/g" android/app/build.gradle
          sed -i "s/versionName \".*\"/versionName \"${{ github.event.inputs.version_name }}\"/g" android/app/build.gradle
          
      - name: Build APK Android
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
      - name: Upload File APK
        uses: actions/upload-artifact@v4
        with:
          name: H-M3U8-App-v${{ github.event.inputs.version_name }}
          path: android/app/build/outputs/apk/debug/app-debug.apk